export const LOAD_ITEM  = 'LOAD_ITEM'
export const DRAW_LOAD_ITEM = 'DRAW_LOAD_ITEM'
export const SUCCESS_LOAD_ITEM = 'SUCCESS_LOAD_ITEM'
export const FAILED_LOAD_ITEM = 'FAILED_LOAD_ITEM'

export const ADD_ITEM  = 'ADD_ITEM'
export const DRAW_ADD_ITEM = 'DRAW_ADD_ITEM'
export const SUCCESS_ADD_ITEM = 'SUCCESS_ADD_ITEM'
export const FAILED_ADD_ITEM = 'FAILED_ADD_ITEM'

export const REMOVE_ITEM  = 'REMOVE_ITEM'
export const DRAW_REMOVE_ITEM = 'DRAW_REMOVE_ITEM'
export const SUCCESS_REMOVE_ITEM = 'SUCCESS_REMOVE_ITEM'
export const FAILED_REMOVE_ITEM = 'FAILED_REMOVE_ITEM'

export const RESEND_ITEM  = 'RESEND_ITEM'
export const DRAW_RESEND_ITEM = 'DRAW_RESEND_ITEM'
export const SUCCESS_RESEND_ITEM = 'SUCCESS_RESEND_ITEM'
export const FAILED_RESEND_ITEM = 'FAILED_RESEND_ITEM'

export const LOAD_TRANSACTION  = 'LOAD_TRANSACTION'
export const DRAW_LOAD_TRANSACTION = 'DRAW_LOAD_TRANSACTION'
export const SUCCESS_LOAD_TRANSACTION = 'SUCCESS_LOAD_TRANSACTION'
export const FAILED_LOAD_TRANSACTION = 'FAILED_LOAD_TRANSACTION'

export const ADD_TRANSACTION  = 'ADD_TRANSACTION'
export const DRAW_ADD_TRANSACTION = 'DRAW_ADD_TRANSACTION'
export const SUCCESS_ADD_TRANSACTION = 'SUCCESS_ADD_TRANSACTION'
export const FAILED_ADD_TRANSACTION = 'FAILED_ADD_TRANSACTION'